TasKit/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView

# pylint: disable=invalid-name
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^basic/', include('basic.urls', namespace='basic')),
    url(r'^$', RedirectView.as_view(url='/basic/home/')),
    url(r'^home/$', RedirectView.as_view(url='/basic/home/')),
]

basic/urls.py
from django.conf.urls import url
from basic.views import (
    HomeView,
    LoginView,
    SignUpView,
    ResetPasswordView,
    ResetPasswordDoneView,
    ResetPasswordConfirmView,
    ResetPasswordCompleteView
)

# pylint: disable=invalid-name
urlpatterns = [
    url(r'^home/$', HomeView.as_view(), name='home'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^signup/$', SignUpView.as_view(), name='signup'),

    url(r'^reset_password/$',
        ResetPasswordView.as_view(),
        name='reset_password'),

    url(r'^reset_password/done/$',
        ResetPasswordDoneView.as_view(),
        {'template_name': 'basic/reset_password_done.html'},
        name='reset_password_done'),

    url(r'^reset_password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)$',
        ResetPasswordConfirmView.as_view(),
        name='password_reset_confirm'),

    url(r'^reset_password/complete/$',
        ResetPasswordCompleteView.as_view(),
        name='password_reset_complete'),
]

basic/models.py
# -*- coding: utf-8 -*-
"""This script contains models required by the basic app."""
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save


class UserProfile(models.Model):
    """User's profile object, an extension to the User model.

    Attributes:
        image (TYPE): url
        user (TYPE): Description
    """

    user = models.OneToOneField(User)
    image = models.ImageField(upload_to='', blank=True)

    def __unicode__(self):
        """Unicode of the UserProfile Model.

        Returns:
            TYPE: String
        """
        return self.user.username.encode('utf-8')

    def __str__(self):
        """string description.

        Returns:
            TYPE: String
        """
        return unicode(self)


# pylint: disable=unused-argument
def create_profile(sender, **kwags):
    """Create User Profile when a user register.

    Args:
        sender (TYPE): User
        **kwags: arguments for creating the user profile
    """
    if kwags['created']:
        UserProfile.objects.create(user=kwags['instance'])

post_save.connect(create_profile, sender=User)

main/models.py
# -*- coding: utf-8 -*-
"""Models for Main."""
from __future__ import unicode_literals

# from django.db import models

# Create your models here.

basic/forms.py
"""Forms of basic app."""
from django import forms
from django.contrib.auth import models
from django.contrib.auth.forms import UserCreationForm


class SignUpForm(UserCreationForm):
    """Used for signing up user.

    Attributes:
        email (TYPE): Email Field
    """

    email = forms.EmailField(required=True)

    class Meta:
        model = models.User
        fields = ('username',
                  'first_name',
                  'last_name',
                  'email',
                  'password1',
                  'password2')

    def save(self, commit=True):
        user = super(SignUpForm, self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
            return user
        return None

basic/views.py
# -*- coding: utf-8 -*-
"""Views for Basic App."""

from __future__ import unicode_literals

from django.shortcuts import render, redirect
from django.views.generic import TemplateView
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.views import (
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView
)
from django.urls import reverse_lazy

from basic.forms import SignUpForm


class ResetPasswordView(PasswordResetView):
    """View for resetting password.

    Attributes:
        email_template_name (str): Description
        success_url (TYPE): Description
        template_name (str): Description
    """

    email_template_name = 'basic/reset_password_email.html'
    success_url = reverse_lazy('basic:reset_password_done')
    template_name = 'basic/reset_password.html'


# pylint: disable=too-many-ancestors
class ResetPasswordDoneView(PasswordResetDoneView):
    """View after user chooses to reset his password.

    Attributes:
        template_name (str): Description
    """

    template_name = 'basic/reset_password_done.html'


# pylint: disable=too-many-ancestors
class ResetPasswordConfirmView(PasswordResetConfirmView):
    """View for confirming to reset password.

    Attributes:
        success_url (TYPE): Description
        template_name (str): Description
    """

    template_name = 'basic/reset_password_confirm.html'
    success_url = reverse_lazy('basic:password_reset_complete')


class ResetPasswordCompleteView(PasswordResetCompleteView):
    """View to indicate resetting password completed.

    Attributes:
        template_name (str): Description
    """

    template_name = 'basic/reset_password_complete.html'


class LoginView(TemplateView):
    """View for user login.

    Attributes:
        template_name (str): Description
    """

    template_name = 'basic/login.html'

    def get(self, request, *args, **kwargs):
        form = AuthenticationForm()
        args = {'form': form}
        return render(request, self.template_name, args)

    def post(self, request):
        """Handle user login request.

        Args:
            request (TYPE): Description

        Returns:
            TYPE: rendered html page
        """
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)
            if user:
                login(request, user)
                sub_path = request.GET.get('next')
                if sub_path:
                    return redirect(sub_path)
                return redirect('basic:home')
        args = {'form': form}
        return render(request, self.template_name, args)


class SignUpView(TemplateView):
    """View for user sign up.

    Attributes:
        template_name (str): Description
    """

    template_name = 'basic/signup.html'

    def get(self, request, *args, **kwargs):
        form = SignUpForm()
        args = {'form': form}
        return render(request, self.template_name, args)

    def post(self, request):
        """Handle user sign up request.

        Args:
            request (TYPE): Description

        Returns:
            TYPE: rendered html page
        """
        form = SignUpForm(data=request.POST)
        if request.method == 'POST':
            if form.is_valid():
                new_user = form.save()
                new_user = authenticate(username=form.cleaned_data['username'],
                                        password=form.cleaned_data['password1'])
                login(request, new_user)
                return redirect('basic:home')
        args = {'form': form}
        return render(request, self.template_name, args)


class HomeView(TemplateView):
    """View for temperoray Home.
    Will be removed after the Main app is implemented.

    Attributes:
        template_name (str): Description
    """

    template_name = 'basic/home.html'

    def post(self, request):
        """Logout user.

        Args:
            request (TYPE): Description

        Returns:
            TYPE: Description
        """
        logout(request)
        return redirect('basic:home')

main/views.py
# -*- coding: utf-8 -*-
"""Views for Main."""
from __future__ import unicode_literals

# from django.shortcuts import render

# Create your views here.

basic/templates/base.html
<!DOCTYPE html>
<html>

<head>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
	 crossorigin="anonymous">
	<!-- {% load static %} -->
	<!-- <link rel="stylesheet" type="text/css" href="{% static 'accounts/style.css' %}"> -->
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/css/materialize.min.css">
	<link rel="stylesheet" href="{% static 'css/background.css'%}">
	<link rel="stylesheet" href="{% static 'css/styled-card.css'%}">
	<link rel="stylesheet" href="{% static 'css/button.css'%}">
	<link rel="stylesheet" href="{% static 'css/layout.css'%}">
	<meta name="viewport" content="width=device-width, initial-scale=1.0" charset="utf-8"> {% block head %}
	<title>TasKit</title>
	{% endblock %}
</head>

<body>
	<div class="background-gradient center-container">
		<!-- Static navbar -->
		<div class="z-depth-5 card-container">
			<div class="background-light-blue decoration-container">
				<span></span>
			</div>
			<div class="form-container">
				{% block body %}
				<h1>Base</h1>
				{% endblock %}
			</div>
		</div>
	</div>
</body>
<script src="http://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
 crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/js/materialize.min.js"></script>
<!-- <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
 crossorigin="anonymous"></script> -->

</html>

basic/templates/basic/home.html
{% extends 'base.html' %}
{% load i18n %}
{% block head %}
	<title>Home</title>
{% endblock %}
{% block body %}
	<div class="container">
		<h1>Home</h1>
		<form method="post">
			{% csrf_token %}
			<button id="logout" type="submit">{% trans 'Logout' %}</button>
		</form>
	</div>
{% endblock %}

basic/templates/basic/login.html
{% extends 'base.html' %} {% load i18n %} {% block body %}
<div class="row">
	<form method="post">
		{% csrf_token %} {{ form.as_p }}
		<button class="btn full round" id="login" type="submit">{% trans 'Login' %}</button>
	</form>
	<div class="float-container">
		<a href="{% url 'basic:reset_password' %}" class="btn-flat float left" id="reset_password">{% trans 'Forget Password' %}</a>
		<a href="{% url 'basic:signup' %}" class="btn-flat float right" id="signup">{% trans 'Sign Up' %}</a>
	</div>
</div> {% endblock %}

basic/templates/basic/reset_password.html
{% extends 'base.html' %} {% load i18n %} {% block body %}
<div class="container">
	<h1>{% trans 'Password reset' %}</h1>
	<p>
		{% trans "Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one." %}
	</p>
	<form method="post">
		{% csrf_token %} {{ form.as_p }}
		<button class="btn" type="submit">{% trans 'Reset' %}</button>
	</form>
</div>
{% endblock %}

basic/templates/basic/reset_password_complete.html
{% extends "base.html" %} {% load i18n %} {% block body %}
<p>{% trans "Your password has been set. You may go ahead and log in now." %}</p>
<form action="{% url 'basic:login' %}">
	<button class="btn round full" type="submit">{% trans 'Log in' %}</button>
</form>
{% endblock %}

basic/templates/basic/reset_password_confirm.html
{% extends "base.html" %}
{% load i18n %}
{% block body %}
	{% if validlink %}
		<p>{% trans "Please enter your new password twice so we can verify you typed it in correctly." %}</p>
		<form method="post">{% csrf_token %}
			<fieldset class="module aligned">
				<div class="form-row field-password1">
					{{ form.new_password1.errors }}
					<label for="id_new_password1">{% trans 'New password:' %}</label>
					{{ form.new_password1 }}
				</div>
				<div class="form-row field-password2">
					{{ form.new_password2.errors }}
					<label for="id_new_password2">{% trans 'Confirm password:' %}</label>
					{{ form.new_password2 }}
				</div>
				<button class="btn round full" type="submit">{% trans 'Change my password' %}</button>
			</fieldset>
		</form>
	{% else %}
		<p>{% trans "The password reset link was invalid, possibly because it has already been used.  Please request a new password reset." %}</p>
	{% endif %}
{% endblock %}

basic/templates/basic/reset_password_done.html
{% extends 'base.html' %}
{% load i18n %}
{% block body %}
	<div class="container">
		<h1>{% trans 'Password reset send' %}</h1>
		<p>
			{% trans "We've emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly." %}
			{% trans "If you don't receive an email, please make sure you've entered the address you registered with, and check your spam folder." %}
		</p>
	</div>
{% endblock %}

basic/templates/basic/reset_password_email.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}
{% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'basic:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% trans "Your login email, in case you've forgotten, is same this email address:" %} {{ user.get_username }}
{% trans "Thanks for using our site!" %}
{% blocktrans %}The {{ site_name }} team{% endblocktrans %}
{% endautoescape %}

basic/templates/basic/signup.html
{% extends 'base.html' %}
{% load i18n %}
{% block body %}
	<div class="container">
		<h1>TasKit</h1>
		<form method="post">
			{% csrf_token %} {{ form.as_p }}
			<button class="btn round full" type="submit">{% trans 'Sign Up' %}</button>
		</form>
	</div>
{% endblock %}